version: "3.7"

services:
  test:
    build: .

  reports :
      build: .
      image: "frankescobar/allure-docker-service"
      environment:
        CHECK_RESULTS_EVERY_SECONDS: 1
        KEEP_HISTORY: "TRUE"
      ports:
        - "4040:4040"
        - "5050:5050"
      volumes:
        - ./report:/code/report


